name: nemo_asr_onnx
description: "A Dart package for Inference of nemo ASR ONNX exports."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for the package.
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  collection: ^1.18.0
  fftea: ^1.5.0 # for FFT operations
  path: ^1.9.0                 # lightweight helper for asset locations
  onnxruntime: ^1.4.0
  flutter:
    sdk: flutter


dev_dependencies:
  test: ^1.25.0  # for writing & running unit tests :contentReference[oaicite:1]{index=1}
  lints: ^5.1.0
  flutter_test:
      sdk: flutter

flutter:
  assets:
    - assets/stt-bm-quartznet15x5-V0.onnx
    - assets/soloni-114m-tdt-ctc-V0.onnx
    - assets/quartznet.vocab

license: MIT

